---
title: "January 21 In-Class: Writing Functions"
author: "Sanyapoom Sirijirakarn"
date: "`r Sys.Date()`"
output: openintro::lab_report
---

```{r load-packages, message=FALSE}
library(tidyverse)
library(openintro)
```

### Exercise 1

Insert any text here.

```{r }
length3 <- function(x) sqrt((x[1]^2)+(x[2]^2)+(x[3]^2))
v1 = c(2, -3, 6)
v2 = c(-2, 4, 7)
length3(v1)
length3(v2)
```

### Exercise 2

```{r }
myvectorops <- function(a,b) {
  structure(list(a= a,b= b, magA= sqrt(a[1]^2+a[2]^2+a[3]^2), magB= sqrt(b[1]^2+b[2]^2+b[3]^2), dotProduct= a[1]*b[1]+a[2]*b[2]+a[3]*b[3],
                 crossProduct= c(a[2]*b[3]-a[3]*b[2],a[3]*b[1]-a[1]*b[3],a[1]*b[2]-a[2]*b[1])), class="myvectorops")
}

print.myvectorops <- function(x, ...){
  cat("Basic Vector Operations", "\n", 
      "a = <", x$a[1], ",", x$a[2], ",", x$a[3], ">, b= <", x$b[1], ",", x$b[2], ",", x$b[3], ">\n", 
      "|a| = ", x$magA, ", |b| = ", x$magB, "\n",
      "dot product: a.b = ", x$dotProduct, "\n",
      "cross product: a x b = <", x$crossProduct[1], ",", x$crossProduct[2], ",", x$crossProduct[3], ">", sep="" )
}

myvectorops(v1,v2)
```

