---
title: "Final Project part 2"
author: "Sanyapoom Sirijirakarn"
date: "`r Sys.Date()`"
output: openintro::lab_report
---

```{r load-packages, message=FALSE}
library(zoo)
library(tidyverse)
library(openintro)
library(albersusa)
library(plotly)
library(shiny)
library(lubridate)
uscovid <- read.csv("https://data.cdc.gov/resource/9mfq-cb36.csv?$limit=2000000")

library(readxl)
url <- "https://www2.census.gov/programs-surveys/popest/tables/2020-2021/state/totals/NST-EST2021-POP.xlsx"
destfile <- "NST_EST2021_POP.xlsx"
curl::curl_download(url, destfile)
uspopulation <- read_excel(destfile, skip = 3)

#uscovid2 <- read.csv("United_States_COVID-19_Cases_and_Deaths_by_State_over_Time.csv")

#uscovidHist <- read.csv("data_table_for_daily_case_trends__the_united_states.csv", skip = 2)
```
``` {r}
uspopulation <- uspopulation %>% mutate(...1 = gsub("\\.", "", ...1))
```

data link:
https://data.cdc.gov/Case-Surveillance/United-States-COVID-19-Cases-and-Deaths-by-State-o/9mfq-cb36

https://data.cdc.gov/Case-Surveillance/COVID-19-Case-Surveillance-Public-Use-Data-with-Ge/n8mc-b4w4

### Setting data

```{r}

#seperate date and time for the api call one
Map <- uscovid %>%
  separate(submission_date, c("date", "time"), sep = "T") %>%
  mutate(date = as.Date(date, "%Y-%m-%d"))

Histogram <- Map %>%
  mutate(tempDate = date) %>%
  separate(tempDate, c("year", "month", "day")) %>%
  mutate(day = as.integer(day), month = as.integer(month), year = as.integer(year),
         count = new_case ) %>%
  transform(avg7 = rollmeanr(count, 7, fill = NA))

#Set NA to 0
Map[is.na(Map)] <- 0

my_map_theme <- function(){
  theme(panel.background=element_blank(),
        axis.text=element_blank(),
        axis.ticks=element_blank(),
        axis.title=element_blank())
}

us_states <- usa_sf("laea")
```

### Covidmap function

```{r}
pickGraph <- function(data = Map, myvar, mydate,varChoices, varYear, varMonth) {
  ifelse(data == "Map", covidmap(myvar,mydate), covidHist(varChoices,varYear,varMonth))
}

covidmap <- function(myvar, mydate) {
  #select data on my variable for a single date to create choropleth map
  my_stat <- enquo(myvar)
  
    covid_date <- Map %>%
    filter(date == mydate) %>%
    select(state, new_case, tot_death, plot_stat = !!my_stat)
    
  if(myvar == "tot_death") {myvar <- "Cumulative Deaths"}
  if(myvar == "new_case") {myvar <- "Positive Cases"}
  if(myvar == "new_death") {myvar <- "Positive Deaths"}
  
  us_states <- usa_sf("laea")
  
  mapdata <- left_join(us_states, covid_date, by = c("iso_3166_2" = "state"))
  
  m <- ggplot(mapdata) +
    geom_sf(aes(fill = plot_stat)) +
    scale_fill_continuous(myvar, low="yellow", high="red", labels = scales::comma) +
    my_map_theme()
  
  ggplotly(m) %>%
    style(hoveron = "fill")
}

covidHist <- function(varChoices, varYear, varMonth) {
  if(varChoices == "new_case") {varChoices <- "Positive Cases"}
  if(varChoices == "new_death") {varChoices <- "Positive Deaths"}
  
  x_axis_labels <- min(1):max(31)
  
  my_stat <- enquo(varChoices)
  
  covid_date_hist <- Histogram %>%
  filter(year == varYear, month == varMonth) %>%
  group_by(year, month, day, date) %>%
  summarize(count = sum(new_case),
            plot_stat = !!my_stat, date)
  
  h <-   ggplot(covid_date_hist, aes(x=day, y=count)) +
    geom_col(color="darkblue", fill="lightblue",position = "dodge")  +
  scale_x_continuous(labels = x_axis_labels, breaks = x_axis_labels, limits = c(1,31)) +
  scale_y_continuous(varChoices, labels = scales::comma, breaks = function(x) unique(floor(pretty(seq(0, (max(x) + 1) * 1.1)))))
  
  ggplotly(h) %>%
    style(hoveron = "fill")
}

```

### Shiny App with Tabs

``` {r}

map_list <- list("Cumulative Deaths" = "tot_death",
                 "Positive Cases" = "new_case",
                 "Positive Deaths" = "new_death")

hist_list <- list("Positive Cases" = "new_case",
                  "Positive Death" = "new_death")

hist_year_list <- list("2020" = "2020", 
                       "2021" = "2021", 
                       "2022" = "2022")

hist_month_list <- list("January" = "1",
                                   "February" = "2",
                                   "March" = "3",
                                   "April" = "4",
                                   "May" = "5",
                                   "June" = "6",
                                   "July" = "7",
                                   "August" = "8",
                                   "September" = "9",
                                   "October" = "10",
                                   "November" = "11",
                                   "December" = "12")

ui <- fluidPage(
    # Application title
    titlePanel("US COVID"),
    tabsetPanel(id = "tab",
                tabPanel(title = "US Covid Choropleth Map", value = "Map",
                             sidebarPanel(selectInput("myvar",
                    "Select a variable to display:",
                    choices = map_list,
                    selected = "tot_death")),
                             sidebarPanel(sliderInput("mydate",
                    "Select a date to display:",
                    min = as.Date("2020-01-22", "%Y-%m-%d"),
                    max = as.Date("2022-03-03", "%Y-%m-%d"),
                    value = as.Date("2022-03-03", "%Y-%m-%d"))
                )),
                tabPanel(title = "US Covid Histogram", value = "Histogram",
                         sidebarPanel(selectInput("varChoices",
                    "Select a variable to display:",
                    choices = hist_list,
                    selected = "new_case")),
                         sidebarPanel(selectInput("varYear",
                    "Select a variable to display:",
                    choices = hist_year_list,
                    selected = "2022")),
                    sidebarPanel(selectInput("varMonth",
                    "Select a variable to display:",
                    choices = hist_month_list,
                    selected = "1"))
                )
    ),
        # Show our plot
        mainPanel(
           plotlyOutput("statPlot")
        )
    )
# Define server logic required to create the graph
server <- function(input, output) {
    
    output$statPlot <- renderPlotly({
        ifelse(input$tab == "Map", covidmap(input$myvar,input$mydate), covidHist(input$varChoices,input$varYear,input$varMonth))
    })
}

shinyApp(ui = ui, server = server)
```

### Shiny App

```{r}
ui <- fluidPage (
      titlePanel("US COVID"),
      
      sidebarLayout(
        sidebarPanel(
          selectInput("myvar",
                    "Select a variable to display:",
                    choices = list("Cumulative Deaths" = "tot_death",
                                   "Positive Cases" = "new_case",
                                   "Positive Deaths" = "new_death"),
                    selected = "tot_death"),
          sliderInput("mydate",
                    "Select a date to display:",
                    min = as.Date("2020-01-22", "%Y-%m-%d"),
                    max = as.Date("2022-03-03", "%Y-%m-%d"),
                    value = as.Date("2022-03-03", "%Y-%m-%d"))
      ),
      
      #Show map
      mainPanel(
        plotlyOutput("map")
      )
  )
)

server <- function(input, output) {
  output$map <- renderPlotly({
    covidmap(input$myvar,input$mydate)
  })
}

shinyApp(ui = ui, server = server)
```



### Shiny App

```{r}
ui <- fluidPage (
      titlePanel("US COVID Histogram"),
      
      sidebarLayout(
        sidebarPanel(
          selectInput("varChoices",
                    "Select a variable to display:",
                    choices = list("Positive Cases" = "new_case",
                                   "Positive Death" = "new_death"),
                    selected = "new_case"),
          selectInput("varYear",
                    "Select a variable to display:",
                    choices = list("2020" = "2020",
                                   "2021" = "2021",
                                   "2022" = "2022"),
                    selected = "2022"),
          selectInput("varMonth",
                    "Select a variable to display:",
                    choices = list("January" = "1",
                                   "February" = "2",
                                   "March" = "3",
                                   "April" = "4",
                                   "May" = "5",
                                   "June" = "6",
                                   "July" = "7",
                                   "August" = "8",
                                   "September" = "9",
                                   "October" = "10",
                                   "November" = "11",
                                   "December" = "12"),
                    selected = "1")
      ),
      
      #Show map
      mainPanel(
        plotlyOutput("map")
      )
  )
)

server <- function(input, output) {
  output$map <- renderPlotly({
    covidHist(input$varChoices,input$varYear,input$varMonth)
  })
}

shinyApp(ui = ui, server = server)
```
# Histogram

``` {r}



  my_stat <- "new_case"
my_stat
mys <- enquo(my_stat)
  mys
us_temp <- Histogram %>%
  filter(year == "2021", month == "3") %>%
  group_by(year, month, day, date) %>%
  summarize(count = sum(new_case)) %>%
      mutate(text = paste("<b> Day:", day ,":</b>\nCount: ", 
                          format(count,big.mark=",",scientific=FALSE), sep="")) 





x_axis_labels <- min(1):max(31)

us_temp %>%
  ggplot(aes(x=day, y=count)) +
    geom_col(color="darkblue", fill="lightblue",position = "dodge")  +
  scale_x_continuous(labels = x_axis_labels, breaks = x_axis_labels, limits = c(1,31)) +
  scale_y_continuous( 1, labels = scales::comma, breaks = function(x) unique(floor(pretty(seq(0, (max(x) + 1) * 1.1))))) +
  labs(y = "plot_stat") 
```
