---
title: "Lab Name"
author: "Author Name"
date: "`r Sys.Date()`"
output: openintro::lab_report
---

```{r load-packages, message=FALSE}
library(tidyverse)
library(openintro)
library(albersusa)
```

### Set Data


```{r }
#Recreate rent burden data; need working directory set to folder that contains
# the original data file that is loaded below
library(readxl)
burden <- read_excel("Apartment List Data -- Cost Burden 2019.xlsx", skip = 1)
burden <- select(burden, -12)
namelist <- c("N_Rent_Households", "Overall_Burden_Rate",
              "Moderate_Burden_Rate", "Severe_Burden_Rate",
              "N_Burden_Overall", "N_Burden_Moderate",
              "N_Burden_Severe", "Median_Rent",
              "Median_Renter_Income")
names(burden) <- c("Location", "Type",
                   paste(namelist, "18", sep="_"),
                   paste(namelist, "17", sep="_"),
                   paste(namelist, "08", sep="_"),
                   paste(namelist, "change_17_18", sep="_"),
                   paste(namelist, "change_08_18", sep="_"))

# Save a copy of the dataset for future use
write_csv(burden, "RentCostBurden.csv")

burden <- read_csv("RentCostBurden.csv")

# Rent burden data for states only
burden_state <- burden %>%
  filter(Type=="State") %>%
  select(Location, Overall_Burden_Rate_18)

# Create theme to remove background elements
my_map_theme <- function(){
  theme(panel.background=element_blank(),
        axis.text=element_blank(),
        axis.ticks=element_blank(),
        axis.title=element_blank())
}

# Prepare county-level rent burden data and merge with map data
burden_county <- burden %>%
  filter(Type=="County") %>%
  select(Location, Overall_Burden_Rate_18, Median_Rent_18) %>%
  separate(Location, c("county", "state"), sep=", ") 

```

### Exercise 0

``` {r}
burden <- read_csv("RentCostBurden.csv")
my_map_theme <- function(){
  theme(panel.background=element_blank(),
        axis.text=element_blank(),
        axis.ticks=element_blank(),
        axis.title=element_blank())
}

# Recreate map data using Alber's projection
us_states <- usa_sf("laea")
ggplot(us_states) + 
  geom_sf()

# Rent median data for states only
median_state <- burden %>%
  filter(Type=="State") %>%
  select(Location, Median_Rent_18)

# Join map data and rent median data
us_states_median <- left_join(us_states, median_state, c("name"="Location"))

ggplot(us_states_median) + 
  geom_sf(aes(fill=Median_Rent_18)) +
  scale_fill_continuous(low="yellow", high="red", labels = scales::comma) +
  guides(fill = guide_colorbar("Median Rate", title.position="top")) +
  theme(legend.position = c(1.02, 0.03), legend.direction = "horizontal",
        legend.text = element_text(angle = 45, hjust = 1, vjust = 1)) +
  my_map_theme() +
  
  labs(title="THE UNITED STATES OF HIGH RENT",
       subtitle= "Apartment List looked at the cost of rent relative to income
       and found the percent of households that were \"cost-burdened\"
       with rent higher than 30% of their income.",
       caption = "Source: Apartment List and Yahoo Finance") +
  theme(plot.title = element_text(hjust=0.5, size = 20)) + 
  theme(plot.subtitle = element_text(hjust=0.5)) +
  theme(plot.caption = element_text(hjust=0))
```

### Exercise 1

```{r}
# Recreate map data using Alber's projection
us_county <- counties_sf("laea")

us_county_WA <- us_county %>%
  filter(state == "Washington")

# Rent median data for states only
burden_county_WA <- burden_county %>%
  filter(state == "WA") %>%
  select(county, Overall_Burden_Rate_18)

# Join map data and rent median data
us_county_burden_WA <- left_join(us_county_WA, burden_county_WA, c("name"="county"))

ggplot(us_county_burden_WA) + 
  geom_sf(aes(fill=Overall_Burden_Rate_18)) +
  scale_fill_continuous(low="yellow", high="red") +
  guides(fill = guide_colorbar("Overall_Burden_Rate_18", title.position="top")) +
  my_map_theme()
```

### Exercise 2

```{r}
us_county <- counties_sf()

us_county_WA <- us_county %>%
  filter(state == "Washington")

# Rent median data for states only
burden_county_WA <- burden_county %>%
  filter(state == "WA") %>%
  select(county, Overall_Burden_Rate_18)

# Join map data and rent median data
us_county_burden_WA <- left_join(us_county_WA, burden_county_WA, c("name"="county"))

ggplot(us_county_burden_WA) + 
  geom_sf(aes(fill=Overall_Burden_Rate_18)) +
  scale_fill_continuous(low="yellow", high="red") +
  guides(fill = guide_colorbar("Overall_Burden_Rate_18", title.position="top")) +
  my_map_theme()
```

### Exercise 3

Higher rent doesn't mean higher overburden rate since a lot of people also have higher income in those higher rent area.

```{r}
us_county <- counties_sf()

us_county_WA <- us_county %>%
  filter(state == "Washington")

# Rent median data for states only
median_county_WA <- burden_county %>%
  filter(state == "WA") %>%
  select(county, Median_Rent_18)

# Join map data and rent median data
us_county_median_WA <- left_join(us_county_WA, median_county_WA, c("name"="county"))

ggplot(us_county_median_WA) + 
  geom_sf(aes(fill=Median_Rent_18)) +
  scale_fill_continuous(low="yellow", high="red") +
  guides(fill = guide_colorbar("Median_Rent_18", title.position="top")) +
  my_map_theme()
```

### Exercise 4

```{r}
NW_states <- counties_sf() %>% filter (state%in%c("Washington", "Oregon", "Idaho"))

# Rent median data for states only
burden_county_NW <- burden_county %>%
  filter(state%in%c("WA", "OR", "ID")) %>%
  select(county, Overall_Burden_Rate_18)

# Join map data and rent burden data
us_county_burden_NW <- left_join(NW_states, burden_county_NW, c("name"="county"))

ggplot(us_county_burden_NW) + 
  geom_sf(aes(fill=Overall_Burden_Rate_18)) +
  scale_fill_continuous(low="yellow", high="red") +
  guides(fill = guide_colorbar("Overall_Burden_Rate_18", title.position="top")) +
  my_map_theme()
```

### Exercise 5

```{r}
burden_county <- burden %>%
  filter(Type=="County") %>%
  select(Location, Overall_Burden_Rate_18, Median_Rent_18) %>%
  separate(Location, c("county", "state"), sep=", ") 

# Join map data and rent median data
us_county_burden <- left_join(counties_sf("laea"), burden_county, c("name"="county"))

ggplot() + 
  geom_sf(data = us_county_burden, aes(fill=Overall_Burden_Rate_18), size = 0.5) +
  geom_sf(data = usa_sf(), alpha=0, size=0.5, color="black") +
  scale_fill_continuous(low="yellow", high="red", labels = scales::comma) +
  guides(fill = guide_colorbar("Overall_Burden_Rate_18", title.position="top")) +
  my_map_theme()
```

### Exercise 6

```{r}
anti_join(burden_county, us_county, by=c("county"="name","state"="iso_3166_2"))

burden_county_2 <- burden_county %>%
  mutate(county = trimws(county),
         county = str_replace(county," Borough", ""))

us_county$name[us_county$name == "St. Louis" & us_county$lsad == "city"] <- 
  "St. Louis City"

anti_join(burden_county_2, us_county, by=c("county"="name","state"="iso_3166_2"))


```
